### ISSUE TITLE
suggest: use tag same as easycwmp.org version

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#1]
easycwmp.org has some versions, but this repo don't have tag ...

suggest: this repo use tags same as easycwmp.org versions
eg.
http://www.easycwmp.org/download/easycwmp-1.0.5.tar.gz 
means
https://github.com/pivasoftware/easycwmp/tree/1.0.5

**Comment by pivasoftware** [comment]
it's ok for the newest version:
EasyCwmp-1.1.0 and EasyCwmp-1.1.1
