### ISSUE TITLE
can't get LANDevice on hiwifi router rom 9005

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#10]
`easycwmp -j get InternetGatewayDevice.LANDevice.`

return error 9005

![easycwmp_error_9005](https://cloud.githubusercontent.com/assets/4971414/5738475/990c5880-9c27-11e4-8128-a1513b043fd0.png)

**Comment by pivasoftware** [comment]
in the image you used

easycwmp -j get InternetGatewayDevice.LANDevice

without dot at the end. It should be

easycwmp -j get InternetGatewayDevice.LANDevice.

**Comment by sinkcup** [comment]
not that reason. I had fix it, see the link above.
