### ISSUE TITLE
can't get dl_size

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#12]
can't get dl_size when there are /tmp and /tmp/storage/mmcblk0p2.
![dl_size](https://cloud.githubusercontent.com/assets/4971414/5772772/edf477a8-9d92-11e4-9162-531b1ed6c10a.png)

**Comment by pivasoftware** [comment]
Please feel free to update the easycwmp script according to your hardware and the openwrt version. The goal of easycwmp is to make easy the change of the data model and the download via scripts
