### ISSUE TITLE
"1 Firmware Upgrade Image" sysupgrade return 141, but manually run ok

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#14]
I upgrade firmware from 0.9007 to 0.9008, then from 0.9008 to 0.9007, over and again.
easycwmp download the firmware to `/tmp/easycwmp_download`, than auto run `sysupgrade`, sometimes ok and auto reboot, sometimes return error 141, but at this time I manually run `/bin/sh /usr/sbin/easycwmp --json json_input` or `/sbin/sysupgrade /tmp/easycwmp_download` are all OK.

![2015-01-19 10 12 46](https://cloud.githubusercontent.com/assets/4971414/5795196/d47a6f7e-9fc4-11e4-8f65-76dc6a14e018.png)
![2015-01-19 10 12 54](https://cloud.githubusercontent.com/assets/4971414/5795198/db7a1716-9fc4-11e4-9eff-928d2dbdf7a4.png)
manually run OK:
![2015-01-19 10 16 44](https://cloud.githubusercontent.com/assets/4971414/5795202/e185dad2-9fc4-11e4-9374-7ed83f58a317.png)

**Comment by sinkcup** [comment]
when display error, and there is a new file `/etc/easycwmp/.backup.xml`, and easycwmp auto exit, and can not start again.
![2015-01-19 14 34 27](https://cloud.githubusercontent.com/assets/4971414/5796749/5bd6bcc0-9fe8-11e4-8483-409eca5bbd2b.png)

**Comment by sinkcup** [comment]
manumally run `easycwmp -j apply download "1 Firmware Upgrade Image"`, success too.
![2015-01-19 15 12 54](https://cloud.githubusercontent.com/assets/4971414/5797048/cc2e1b4e-9fed-11e4-9e79-2feec2a88317.png)

**Comment by pivasoftware** [comment]
Please feel free to update the easycwmp script according to your hardware and the openwrt version. The goal of easycwmp is to make easy the change of the data model and the download via scripts
