### ISSUE TITLE
2.4G and 5G should be "LANDevice.1." and "LANDevice.2."

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#15]
one route support 2.4G and 5G, now easycwmp use "LANDevice.1.", should be "LANDevice.1." and "LANDevice.2."

![5G wireless config](https://cloud.githubusercontent.com/assets/4971414/5811591/2438c036-a094-11e4-9f36-9a8f5bc893a3.png)
![LANDevice.1.](https://cloud.githubusercontent.com/assets/4971414/5811594/2e378b62-a094-11e4-8f7e-ce5e1fd9d256.png)

**Comment by sinkcup** [comment]
done.
![2015-01-20 18 14 42](https://cloud.githubusercontent.com/assets/4971414/5815380/3d2445d4-a0d0-11e4-8fdb-ea7b47c7cca5.png)

**Comment by pivasoftware** [comment]
Please feel free to update the easycwmp script according to your hardware and the openwrt version. The goal of easycwmp is to make easy the change of the data model and the download via scripts
