### ISSUE TITLE
change os user's password

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#19]
date model : 

 * InternetGatewayDevice.User.
 * InternetGatewayDevice.User.1.
 * InternetGatewayDevice.User.1.Username
 * InternetGatewayDevice.User.1.EncryptedPassword
 * InternetGatewayDevice.User.1.LastChanged

**Comment by sinkcup** [comment]
done
![2015-01-27 18 33 42](https://cloud.githubusercontent.com/assets/4971414/5917002/0a50fb56-a653-11e4-991c-bddd7654b407.png)

**Comment by pivasoftware** [comment]
Please feel free to add the parameter you want in the easycwmp script according to your hardware and the openwrt version. The goal of easycwmp is to make easy the change of the data model and the download via scripts
