### ISSUE TITLE
1.0.5 can't get InternetGatewayDevice.LANDevice.

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#2]
version 1.0.5 on openwrt, run this:

`easycwmp --json get InternetGatewayDevice.`

output "InternetGatewayDevice.WANDevice.", but no "InternetGatewayDevice.LANDevice."

    { "parameter": "InternetGatewayDevice.DeviceInfo.Manufacturer", "fault_code": "", "value": "hiwifi.com", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.ManufacturerOUI", "fault_code": "", "value": "hiwifi", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.ProductClass", "fault_code": "", "value": "j1s_easycwmp", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.SerialNumber", "fault_code": "", "value": "D4EE071313FC", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.HardwareVersion", "fault_code": "", "value": "HC5661", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.SoftwareVersion", "fault_code": "", "value": "0.9008.2.8061s", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.UpTime", "fault_code": "", "value": "1689", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.DeviceLog", "fault_code": "", "value": "", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.SpecVersion", "fault_code": "", "value": "1.0", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.DeviceInfo.ProvisioningCode", "fault_code": "", "value": "", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.URL", "fault_code": "", "value": "http:\/\/192.168.10.173:7547\/", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.Username", "fault_code": "", "value": "easycwmp", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.Password", "fault_code": "", "value": "easycwmp", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.PeriodicInformEnable", "fault_code": "", "value": "1", "type": "xsd:boolean" }
    { "parameter": "InternetGatewayDevice.ManagementServer.PeriodicInformInterval", "fault_code": "", "value": "100", "type": "xsd:unsignedInt" }
    { "parameter": "InternetGatewayDevice.ManagementServer.PeriodicInformTime", "fault_code": "", "value": "0001-01-01T00:00:00Z", "type": "xs:date" }
    { "parameter": "InternetGatewayDevice.ManagementServer.ConnectionRequestURL", "fault_code": "", "value": "http:\/\/192.168.10.229:7547\/", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.ConnectionRequestUsername", "fault_code": "", "value": "easycwmp", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.ConnectionRequestPassword", "fault_code": "", "value": "easycwmp", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.X_easycwmp_org__ACS_Scheme", "fault_code": "", "value": "http", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.X_easycwmp_org__ACS_Hostname", "fault_code": "", "value": "192.168.10.173", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.X_easycwmp_org__ACS_Port", "fault_code": "", "value": "7547", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.X_easycwmp_org__ACS_Path", "fault_code": "", "value": "\/", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.X_easycwmp_org__Connection_Request_Port", "fault_code": "", "value": "7547", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.ManagementServer.ParameterKey", "fault_code": "", "value": "", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionStatus", "fault_code": "", "value": "Connected", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress", "fault_code": "", "value": "192.168.10.229", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress", "fault_code": "", "value": "D4:EE:07:13:13:FD", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Enable", "fault_code": "", "value": "1", "type": "xsd:boolean" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Username", "fault_code": "", "value": "", "type": "xsd:string" }
    { "parameter": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Password", "fault_code": "", "value": "", "type": "xsd:string" }

**Comment by pivasoftware** [comment]
you have to put wireless config file under /etc/config
