### ISSUE TITLE
suggest: use 4 space not tab, same as most coding standards

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#3]
When I read ext/openwrt/scripts/functions/lan_device, I find it use tab not 4 space ...
It's strange.
suggest: use 4 space not tab, same as most coding standards

**Comment by sinkcup** [comment]
and there is error "noeol" in vim, I fix it too.

**Comment by pivasoftware** [comment]
We have our own rules and reasons to use tab and not 4 spaces
