### ISSUE TITLE
Can't connect to ACS via Digest.

### ISSUE THREAD

**Issue by ztpaul** [pivasoftware/easycwmp#47]
Hi,

CPE Can't connect to ACS via Digest.
I have compiled libcurl with openssl instead of wolfssl, it didn't work too.

Pls see the attachment for details. Thanks

[DigestFail.zip](https://github.com/pivasoftware/easycwmp/files/8386229/DigestFail.zip)

**Comment by ballzb** [comment]
Open the following option  will make digest works well.
make menuconfig---> Libraries ---> libcurl--->Enable cryptographic authentication

**Comment by ztpaul** [comment]
Open the following option  will make digest works well.
make menuconfig---> Libraries ---> libcurl--->Enable cryptographic authentication
