### ISSUE TITLE
can't get ssid on hiwifi router rom 9008

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#6]
device: hiwifi HC5661 
rom: 0.9006.2.6020s and 0.9008.2.8061s
`easycwmp -j get InternetGatewayDevice.`  are all ok, but acs(genieacs) receive different.
9008 can't report ssid and InternetGatewayDevice.DeviceInfo.DeviceLog to acs.
maybe because 0.9008.2.8061s use special /etc/config/wireless
![9006 is ok](https://cloud.githubusercontent.com/assets/4971414/5719885/cd6c16ea-9b57-11e4-81ac-9e0a763c9af2.png)
![9008 have not ssid](https://cloud.githubusercontent.com/assets/4971414/5719909/0e80adbc-9b58-11e4-8035-60c33f9edbba.png)

**Comment by sinkcup** [comment]
0.9008.2.8061s use special /etc/config/wireless

	config wifi-device 'radio0'                                                     
		option type 'ralink'                                                    
		option channel '0'                                                      
		option txpwr 'max'                                                      
		                                                                        
	config wifi-iface 'master'                                                      
		option device 'radio0'                                                  
		option ifname 'ra0'                                                     
		option ifname2 'rai0'                                                   
		option network 'lan'                                                    
		option mode 'ap'                                                        
		option encryption 'none'                                                
		option ssid 'HiFree-test-ios7_8'                                        
		option disabled '1'                                                     
		option instance '1'                                                     
		                                                                        
	config wifi-iface 'slave'                                                       
		option device 'radio0'                                                  
		option ifname 'apcli0'                                                  
		option network 'lan'                                                    
		option mode 'sta'                                                       
		option ssid 'HiWiFi_1309F6'                                             
		option encryption 'none'                                                
		option disabled '1'                                                     
		option instance '2'                                                     
		                                                                        
	config wifi-iface 'guest'                                                       
		option device 'radio0'                                                  
		option ifname 'ra1'                                                     
		option ifname2 'rai1'                                                   
		option network 'lan'                                                    
		option mode 'ap'                                                        
		option ssid 'HiWiFi_guest'                                              
		option encryption 'none'                                                
		option isolate '1'                                                      
		option disabled '1'                                                     
		option instance '3'

**Comment by pivasoftware** [comment]
yes as you said, you are using special /etc/config/wireless. you have to update the lan_device script.
