### ISSUE TITLE
auto get manufacturer,oui,product_class,serial_number,hardware_version,software_version

### ISSUE THREAD

**Issue by sinkcup** [pivasoftware/easycwmp#7]
`/etc/config/easycwmp` default config is:

     config device                                      
        option manufacturer easycwmp               
        option oui FFFFFF                          
        option product_class easycwmp              
        option serial_number FFFFFF123456          
        option hardware_version example_hw_version 
        option software_version example_sw_version

by change /usr/share/easycwmp/functions/device_info, let it auto get from openwrt os, don't need edit config manually.

**Comment by sinkcup** [comment]
ok
![2015-01-13 20 12 40](https://cloud.githubusercontent.com/assets/4971414/5720547/8d9c0580-9b60-11e4-8a82-d9d458a294bc.png)

**Comment by pivasoftware** [comment]
Please feel ffree to change the device_info script in order to get the device info value from the right place in OpenWRT os
